services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - '4200:4200'
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true